---
language: python
sudo: required

env: PLUGIN=metadata

services:
  - docker

before_install:
  - git clone  git://github.com/openmicroscopy/omero-test-infra .omero

script:
  - .omero/cli-docker

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
